# -*- coding: utf-8 -*-
"""Mirror app configs from the source tree into the Worker's served tree.

The deployed Worker serves the frontend from ``worker/public`` (see the
``[assets]`` block in ``worker/wrangler.toml``). The apps you edit live in the
source tree ``apps/``. This script keeps the two in sync so a change under
``apps/`` actually reaches the live frontend:

- copies every ``apps/<slug>/app.config.json`` -> ``worker/public/apps/<slug>/app.config.json``
- regenerates ``worker/public/apps/registry.json`` from ``apps/registry.json``,
  rewriting each ``config`` path from ``../apps/<slug>/..`` (relative — the local
  dev launcher ``app/index.html``) to ``/apps/<slug>/..`` (absolute, same-origin —
  the production launcher ``worker/public/index.html``).
- prunes orphan app folders under ``worker/public/apps`` that no longer exist in ``apps/``.

It does NOT touch ``index.html``: ``app/index.html`` (local dev, manual API URL)
and ``worker/public/index.html`` (production, same-origin API + support bar) are
intentionally different files.

Run by hand, or automatically from ``tools/new_app.py`` and the deploy runners:
    python tools/sync_public.py
"""
import os, re, json, sys, shutil

if hasattr(sys.stdout, "reconfigure"):
    try: sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception: pass

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_APPS = os.path.join(ROOT, "apps")
SRC_REG = os.path.join(SRC_APPS, "registry.json")
PUB_APPS = os.path.join(ROOT, "worker", "public", "apps")
PUB_REG = os.path.join(PUB_APPS, "registry.json")


def atomic_write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".part"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text); f.flush(); os.fsync(f.fileno())
    os.replace(tmp, path)


def to_abs(cfg_path):
    """'../apps/todo/app.config.json' -> '/apps/todo/app.config.json' (same-origin)."""
    m = re.search(r"apps/.*$", cfg_path or "")
    return "/" + m.group(0) if m else cfg_path


def _read_json(path):
    return json.load(open(path, encoding="utf-8"))


def source_slugs():
    """Slugs REGISTERED in apps/registry.json that also have a config file.
    Unregistered apps/<slug>/ folders are inactive reference patterns — neither
    served into worker/public nor shown in the launcher (register them to activate)."""
    try:
        reg = json.load(open(SRC_REG, encoding="utf-8"))
    except Exception:
        return []
    out = []
    for a in reg.get("apps", []):
        m = re.search(r"apps/([^/]+)/", a.get("config", ""))
        slug = m.group(1) if m else None
        if slug and os.path.isfile(os.path.join(SRC_APPS, slug, "app.config.json")):
            out.append(slug)
    return out


def drift():
    """Return a list of human-readable reasons the served tree is out of sync.
    Empty list means apps/ and worker/public/apps/ match."""
    issues = []
    for slug in source_slugs():
        src = os.path.join(SRC_APPS, slug, "app.config.json")
        pub = os.path.join(PUB_APPS, slug, "app.config.json")
        if not os.path.exists(pub):
            issues.append(f"{slug}: missing in worker/public")
        elif open(src, encoding="utf-8").read() != open(pub, encoding="utf-8").read():
            issues.append(f"{slug}: config differs from worker/public")
    # registry
    try:
        want = {"apps": [{"name": a.get("name"), "icon": a.get("icon"),
                          "config": to_abs(a.get("config", ""))}
                         for a in _read_json(SRC_REG).get("apps", [])]}
        have = _read_json(PUB_REG)
        if have.get("apps") != want["apps"]:
            issues.append("registry.json differs from worker/public")
    except Exception:
        issues.append("registry.json unreadable in one of the trees")
    # orphans
    if os.path.isdir(PUB_APPS):
        src_set = set(source_slugs())
        for name in sorted(os.listdir(PUB_APPS)):
            d = os.path.join(PUB_APPS, name)
            if os.path.isdir(d) and name not in src_set:
                issues.append(f"{name}: orphan folder in worker/public (not in apps/)")
    return issues


def sync(verbose=True):
    """Make worker/public/apps mirror apps/. Returns the list of actions taken."""
    actions = []
    slugs = source_slugs()

    # 1) copy each app config
    for slug in slugs:
        src = os.path.join(SRC_APPS, slug, "app.config.json")
        pub = os.path.join(PUB_APPS, slug, "app.config.json")
        text = open(src, encoding="utf-8").read()
        if not os.path.exists(pub) or open(pub, encoding="utf-8").read() != text:
            atomic_write(pub, text)
            actions.append(f"copied {slug}/app.config.json")

    # 2) regenerate registry with same-origin (absolute) config paths
    src_reg = _read_json(SRC_REG)
    out_reg = {
        "_comment": "GENERATED by tools/sync_public.py from apps/registry.json — do not edit by hand. "
                    "Served by the Worker at the same origin; config paths are absolute (site root).",
        "apps": [{"name": a.get("name"), "icon": a.get("icon"),
                  "config": to_abs(a.get("config", ""))}
                 for a in src_reg.get("apps", [])],
    }
    out_text = json.dumps(out_reg, ensure_ascii=False, indent=2) + "\n"
    if not os.path.exists(PUB_REG) or open(PUB_REG, encoding="utf-8").read() != out_text:
        atomic_write(PUB_REG, out_text)
        actions.append("wrote registry.json")

    # 3) prune orphan app folders
    if os.path.isdir(PUB_APPS):
        src_set = set(slugs)
        for name in sorted(os.listdir(PUB_APPS)):
            d = os.path.join(PUB_APPS, name)
            if os.path.isdir(d) and name not in src_set:
                shutil.rmtree(d)
                actions.append(f"pruned orphan {name}/")

    if verbose:
        if actions:
            for a in actions:
                print("  " + a)
            print(f"Synced worker/public/apps  ({len(actions)} change(s)). Redeploy to go live.")
        else:
            print("worker/public/apps already in sync.")
    return actions


if __name__ == "__main__":
    sync()
